### DISCUSSION TITLE
OpenFGA command to run health checks (useful for docker compose)

### DISCUSSION THREAD

**Discussion by rhamzeh** [openfga/community#109] [Ideas]
**Suggested by**: @MidasLamb on Discord
**Summary**: Currently, there is no way to do a healthcheck of openfga in docker compose from within the image itself

**Possible Solutions**:
1. Bundle curl into the docker image
  - How it helps: It would allow calling our http endpoint for healthcheck requests
  - Cons: increased size and attack vector due to more bundled tooling
  ```yaml
    healthcheck:
      test: ["CMD", "curl", "-X", "GET", "-d", "'{\"service\":\"openfga.v1.OpenFGAService\"}'" http://localhost:8080/healthz"]
      interval: 10s
      timeout: 20s
      retries: 5
  ```
 
2. Bundle grpc tooling into the docker image
  - How it helps: It would allow calling our grpc endpoint for healthcheck requests, it would be consistent with other CNCF projects that utilize grpc
  - Cons: increased size and attack vector due to more bundled tooling
  ```yaml
    healthcheck:
      test: ["CMD", "grpcurl", "-plaintext", "-d", "'{\"service\":\"openfga.v1.OpenFGAService\"}'" localhost:8081 grpc.health.v1.Health/Check"]
      interval: 10s
      timeout: 20s
      retries: 5
  ```
 
3. Expose a command line (like `run`, for example `is-healthy` or `check-health`)
  - How it helps: it would re-use the plumbing we have for the grpc/http endpoint, it wouldn't need additional tools to be installed
  - Cons: Why when standard tooling is available?
  ```yaml
    healthcheck:
      test: ["CMD", "openfga", "is-healthy"]
      interval: 10s
      timeout: 20s
      retries: 5
  ```

What we care about?
- Not re-inventing the wheel
- Following conventions established by other projects in the CNCF and the OSS world
- Reducing security and maintenance impact
- Satisfying the use-case

Let's have a discussion on the best way forward here and start an issue once we reach a decision so that we can move forward
