### DISCUSSION TITLE
How to model viewer from owner domain

### DISCUSSION THREAD

**Discussion by agale031176** [openfga/community#152] [Q&A] [answered]
Is it possible to model the scenario that a viewer has to be a user and a user from the domain of owner's domain? I am trying to model it something like this:

```
model
  schema 1.1
type user
type domain
  relations
    define member: [user,domain#member]
type board
  relations
    define owner: [user,domain#member]
    define parent: [folder]
    define viewer:  [user, owner#domain] or owner or viewer from parent
```
    
 owner#domain is not correct but I am not sure how to represent it.

**Comment by rhamzeh** [comment, marked as answer]
You can do something like:

```py
model
  schema 1.1
type user
  relations
    define domain: [domain]
    define coworker: member from domain
type domain
  relations
    define member: [user]
type board
  relations
    define owner: [user]
    define parent: [folder]
    define viewer:  [user] or owner or viewer from parent
    define can_view: viewer and coworker from owner
```

Make sure when a user is added to a domain that you write two tuples:
```yaml
- user: user:carl
  relation: member
  object: domain:contoso
- user: domain:contoso
  relation: domain
  object: user:carl
```
