### DISCUSSION TITLE
Get all tuples related to a user without specifying relation or object

### DISCUSSION THREAD

**Discussion by oasisk** [openfga/community#251] [Ideas]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [Discord](https://discord.gg/8naAwJfWN6) community and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Our model allows custom role creation & assigning permissions to this role on pre-defined resources, the permissions are get , list , create , update & delete. 

Our model is as described in Store data.

We would like to fetch all permissions that role:role1 has, read or list objects API cant help us fetch us because of mandatory request attributes each of API's have   

### Expectation

We would like to fetch all permission tuples for role:role1

### Reproduction

model specified above

### Store data

```yaml
model_file: |
 model
  schema 1.1

type user

type org
  relations
    define viewer: [user]
    define editor: [user]

type folder
  relations
    define GET: [user, role#assignee] or viewer from owningOrg
    define POST: [user, role#assignee] or editor from owningOrg
    define owningOrg: [org]


type dashboard
  relations
    define GET: [user, role#assignee] or viewer from owningOrg
    define POST: [user, role#assignee] or editor from owningOrg
    define owningOrg: [org]

type function
  relations
    define GET: [user, role#assignee] or viewer from owningOrg
    define POST: [user, role#assignee] or editor from owningOrg
    define owningOrg: [org]

type role
  relations
    define assignee: [user] 
    define viewer: [user]

tuples:
  - user: a@a.com
    relation: assignee
    object: role:role1
  - user: role:role1#assignee
    relation: POST
    object: function:a
```

### OpenFGA version

v1.4.0

### How are you running OpenFGA?

In Docker

### What datastore are you using?

Postgres

### OpenFGA Flags

NA
