### DISCUSSION TITLE
How to model multi-tenancy where the same user (logged in user that is) can have multiple tenant-users, each with a different set of permissions?

### DISCUSSION THREAD

**Discussion by OsmanMElsayed** [openfga/community#446] [Q&A] [answered]
Hi folks,

I'm working with a multi-tenant app, where there are these entities:
- Principal (identified by the sub claim from a JWT token)
- Tenant
- Tenant-User

Where:
- The principal, can access multiple tenants (i.e. it can have zero or more associated tenant users). Where in each one of those tenants, the set of permissions are scoped to the tenant user linked to the principal.
- Coming to the more interesting part: The principal, can have multiple users within the same tenant with different set of permissions

What I want to achieve:
- I want to do authZ checks to verify that the tenant user has a certain relation with the tenant - I cannot do this check at the level of the principal because the principal can be associated with multiple tenant-users in the same tenant
- I want to ensure that the principal is associated with the tenant user - otherwise the principal can access any tenant user
- I want to perform these two checks in one check request, ideally, as I want to avoid batching multiple checks.
- I want to be able to do a reverse index query, i.e., "give me all the tenant-users that the principal is associated with".

The best I could come up with is to used conditions and contextual tupples:

```
model
    schema 1.1

  type tenant_user
  
  type tenant
    relations
      define member: [tenant_user with valid_current_principal_context]
      
      define reader: [tenant_user] and member
      define writer: [tenant_user] and member
      
      can_manage_users: writer
      
  condition valid_current_principal_context(tenant_user_linked_principal_id: string, current_principal_id: string) {
    tenant_user_linked_principal_id == current_principal_id
  }
```

Example of tuple stored in DB:
```
- user: tenant_user:john_doe
  relation: member
  object: tenant:acme
  condition:
    name: valid_current_principal_context
    context:
      tenant_user_linked_principal_id: 00000000-0000-0000-0000-000000000000
```

The check:

```
- user: user:john_doe
  object: tenant:acme
  context:
    current_principal_id: 00000000-0000-0000-0000-000000000000 # Comes from the principal's active session
  assertions:
    member: true
```

I've super curious would you approach this?
