### DISCUSSION TITLE
Is it possible to set multiple model_files in the .fga.yaml file for tests?

### DISCUSSION THREAD

**Discussion by freckie** [openfga/community#465] [Q&A] [answered]
My schema is split into two files: `core.fga` and `registry/registry.fga`.
core.fga defines the core module, registry.fga defines registry-related types.

I'm writing `registry_test.fga.yaml` for testing the registry, but I can’t make tuples referring to `user` which defined in `core.fga`.
The error message is (using vscode extension):
```
tuples.1.user invalid type 'user'. Valid types are [user_group,repo_group,repo]OpenFGAYamlValidationError
```

I guess it is because I split the schema into modules; core and registry.
If I could specify multiple model_file fields in the .fga.yaml file, it would probably solve the problem.
Is there any other way to handle this problem?

---

```
./
├── core.fga
├── fga.mod
└── registry/
    ├── registry.fga
    └── registry_test.fga.yaml
```

```yaml
# core.fga
module core

type user_group
  relations
    define admin: [user]
    define member: [user] or admin

type user
```

```yaml
# registry/registry.fga
module registry

type repo_group
  relations
    define owner_group: [user_group]
```

```yaml
# registry/registry_test.fga.yaml
name: registry test

model_file: ./registry.fga

tuples:
  - user: user_group:0
    relation: owner_group
    object: repo_group:0

  - user: user:00  # << error
    relation: admin
    object: user_group:0
```
