### DISCUSSION TITLE
How to design model for resource specific access and also allowing  access to all the resources?

### DISCUSSION THREAD

**Discussion by prsanjay** [openfga/community#473] [Q&A] [answered]
Hi Everyone,

I have a multi-tenant app where we first create the account and then add users to it. We also create the groups and roles under the account. The same user can be present in multiple accounts, but groups and roles are owned by a specific account and can not be shared across accounts. 

Currently we are having authorization mechanism where users can create their custom roles by selecting the fine-grained permissions. Here role is a collection or container of the related permissions. If I take the example of a resource fund, then fund.create, fund.read, fund.update, fund.delete are the permissions, and users can create custom roles by selecting those permissions. The user can only assign those roles to the group and not to the users.  When user logs in and try to create the fund, we check if the user is present in the group which has the role that contains fund.create permission, and if so, then only allow to create the fund. If user creates a custom role called Fund Manager and select all the above permissions and assign that role to say Group Fund Manager within that account then all the users present in that group for that account would be able to create the funds, update all the funds present in the account, read all the funds and delete all the funds present in the account. But along with this we also have a scenario where lets say we have a resource called questionnaires, and questionnaires are having a sections.  Now, here we want to make sure only Group-1 can have section.read and section.write permission on section-1 and group-2 has access of section-2. Right now, we store section_id, group_id and role_id mapping to the database for this and then checking the access resource specific checks.

We also have a concept of modules where we assign the modules to the accounts and when we add users to the account we select which module access the user should have and when the user tries to access the module first we check if the user really have access of that module and if so then we perform other regular authorization checks.

Now, we want to use OpenFGA to remove the manual checks we are doing, and I designed the model as below.  I have 2 questions

1. Is the model below designed correctly? I am completely new to OpenFGA
2. Can I check module access for the user and regular authorization check in a single request? If so, how? I am not able to come up with model design for that.

```
model
  schema 1.1

type user

type account
  relations
    define belongs_to: [user]

type group
  relations
    define member: [user]

type role
  relations
    define assigned: [group#member]

type section
  relations
    define section_delete: [role#assigned]
    define section_edit: [role#assigned]
    define section_read: [role#assigned] or section_edit
    define section_update: [role#assigned]

type fund
  relations
    define fund_create: [role#assigned]
    define fund_delete: [role#assigned]
    define fund_update: [role#assigned]

type module
  relations
    define subscribed_to: [account] # anything else should go here?
```

Your help will be greatly appreciated. Many Thanks

**Comment by aaguiarz** [comment]
Hi @prsanjay 

The model looks good! Regarding `module`, is there a way you can relate it to other types? E.g. does a section/fund belong to a module?

**Reply by prsanjay** [reply]
Hi @aaguiarz, Thanks for the prompt reply. And yes, all the resources, like section/fund belongs to specific module.

**Comment by aaguiarz** [comment]
Would something like this work?

```
type module
  relations
    define subscribed_to: [account] 

type section
  relations
    define module : [module]
    define section_delete: [role#assigned] and subscribed_to from module
    define section_edit: [role#assigned]  and subscribed_to from module
    define section_read: [role#assigned] or section_edit  and subscribed_to from module
    define section_update: [role#assigned]  and subscribed_to from module

type fund
  relations
    define module : [module]
    define fund_create: [role#assigned]  and subscribed_to from module
    define fund_delete: [role#assigned]  and subscribed_to from module
    define fund_update: [role#assigned]  and subscribed_to from module
```

**Reply by prsanjay** [reply]
Hi @aaguiarz Thanks again. In my case the whole scenario for module access is as below. 

1. The Account-A is created and assigned say module-A and module-B
2. The Account-B is created and assigned say Module-A and Module-C
3. User John is added to Account-A and given the access of only module-B
4. Same User John is added to Account-B and given the access of only module-C

When John logs in-to the Account-B and tries to access Module-A -- the request should be denied as John#Account-B does not have Module-A access.

How to model this?

**Reply by aaguiarz** [reply]
You'd need to resort to a [contextual tuple](https://openfga.dev/docs/interacting/contextual-tuples) to express the fact that a user is logged in on a specific account.

You can [run the file below with the CLI](https://openfga.dev/docs/modeling/testing), that demos the scenario you describe. Let me know if that makes sense.

```
model: |
  model 
     schema 1.1

    type user

    type account
      relations
        define belongs_to: [user]
        define user_in_context : [user] and belongs_to

    type module
      relations
        define subscribed_to: [account] 
        define has_access: [user] and user_in_context from subscribed_to

tuples:

# The Account-A is created and assigned say module-A and module-B
- user: account:A
  relation: subscribed_to
  object: module:A

- user: account:A
  relation: subscribed_to
  object: module:B

# The Account-B is created and assigned say Module-A and Module-C
- user: account:B
  relation: subscribed_to
  object: module:A

- user: account:B
  relation: subscribed_to
  object: module:C

# User John is added to Account-A and given the access of only module-B
- user: user:john
  relation: belongs_to
  object: account:A

- user: user:john
  relation: has_access
  object: module:B

# Same User John is added to Account-B and given the access of only module-C
- user: user:john
  relation: belongs_to
  object: account:B

- user: user:john
  relation: has_access
  object: module:C


tests:
    - name: When user John is logged in to account A should access only module B
      tuples:
        # This tuple is sent as a contextual tuple
        - user: user:john
          relation: user_in_context
          object: account:A
      check:
        - user: user:john
          object: module:A
          assertions:
            has_access: false

        - user: user:john
          object: module:B
          assertions:
            has_access: true            

        - user: user:john
          object: module:C
          assertions:
            has_access: false                  

    - name: When user John is logged in to account B should access only module C
      tuples:
        # This tuple is sent as a contextual tuple
        - user: user:john
          relation: user_in_context
          object: account:B
      check:
        - user: user:john
          object: module:A
          assertions:
            has_access: false

        - user: user:john
          object: module:B
          assertions:
            has_access: false            

        - user: user:john
          object: module:C
          assertions:
            has_access: true        
```
