### DISCUSSION TITLE
Ability to configure datastore in a more atomic way

### DISCUSSION THREAD

**Discussion by alexandrebrg** [openfga/community#96] [Ideas]
One of the issue we've encountered while using OpenFGA is that we cannot configure the datastore field by field, for now, we expect a full URI to connect. This is a request to add a way to configure field by field the datastore.

## What are the use case of this feature ?

* Deployment in cloud systems where password is provided by a third-party (e.g [Vault](https://www.vaultproject.io/)) through environment variables
* Developer Experience, I believe it can be more convenient to be able to configure individually each fields, instead of providing a composed uri (e.g. in bash scripts)

## How it would impact the configuration ?

In addition to the current configuration, we would be able to configure with atomic fields. It would introduce sub-sections for each database type, as each of them got a specific way to be configured.

### PostgreSQL

```yaml
# file: postgres-config.yaml
datastore:
  engine: postgres

  postgres:
    username: postgres
    password: postgres
    host: localhost
    port: 5432
    database: myDatabase
    secure: false
    schema: public
authn:
  method: preshared
  preshared:
    keys: ["key1", "key2"]
```

### MySql

```yaml
# file: mysql-config.yaml
datastore:
  engine: mysql
  mysql:
    username: root
    password: secret
    host: localhost
    port: 5432
    database: openfga
    # ?parseTime=true parameter would be enforced in openfga codebase

authn:
  method: preshared
  preshared:
    keys: ["key1", "key2"]
```
